name: hiv
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: #пакет для поддержки локализации в Flutter
    sdk: flutter
  bloc: ^9.2.0 #для управления состоянием приложения
  flutter_bloc: ^9.1.1 #интеграция BLoC с Flutter
  go_router: ^17.2.0 #для управления навигацией в приложении
  intl: ^0.20.2 #для интернационализации приложения
  image_picker: ^1.2.1 #для выбора изображений из галереи или камеры
  url_launcher: ^6.3.2 #для открытия URL-адресов в браузере или других приложениях
  equatable: ^2.0.8  #для сравнения объектов
  flutter_map: ^8.3.0 #для отображения карт

  firebase_core: ^4.5.0 #для инициализации Firebase в приложении
  firebase_auth: ^6.2.0 #для аутентификации пользователей
  cloud_firestore: ^6.2.0 #для работы с базой данных Firestore
  firebase_storage: ^13.2.0 #для хранения файлов в Firebase
  google_sign_in: ^7.2.0 #для аутентификации через Google
  logger: ^2.7.0 #для логирования
  firebase_messaging: ^16.1.3  #для работы с push-уведомлениями

  flutter_dotenv: ^6.0.0 #для загрузки переменных окружения из .env файла
  permission_handler: ^12.0.1 #для управления разрешениями, позволяет запрашивать и проверять разрешения
  geolocator: ^14.0.2 #для получения геолокации пользователя
  sizer: ^3.1.3 #для адаптивного дизайна, позволяет создавать интерфейс
  shared_preferences: ^2.5.5 #для хранения данных на устройстве
  flutter_secure_storage: ^10.0.0 #для безопасного хранения данных
  cupertino_icons: ^1.0.9 #для использования иконок в стиле iOS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 #для статического анализа кода и обеспечения его качества
  very_good_analysis: ^10.2.0 #для расширенного статического анализа кода
  flutter_native_splash: ^2.4.7 #для создания нативного сплэш-экрана
  flutter_launcher_icons: ^0.14.4 #для генерации иконок приложения

flutter:
  generate: true 
  assets:
    - .env
    - assets/icons/
  uses-material-design: true


flutter_native_splash:
  color: "#9FFFF9"
  color_dark: "#1A2E2D"
  image: "assets/icons/splash_icon.png"
  image_dark: "assets/icons/splash_icon.png"
  fullscreen: false
  android_12:
    color: "#9FFFF9"
    color_dark: "#1A2E2D"
    image: "assets/icons/splash_icon.png"
    icon_background_color: "#9FFFF9"
    icon_background_color_dark: "#1A2E2D"
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon_adaptive_fg.png"
  adaptive_icon_background: "assets/icons/app_icon_adaptive_bg.png"
  remove_alpha_ios: true
  web:
    generate: false
  min_sdk_android: 21